window.alert("Hello World!");
window.alert(123456789);
window.alert("lorem ispum dummy text");
window.alert("This is windows.alert() practice in JS");
window.alert("The quick brown fox jumps over the lazy dog");
window.alert("Your flight number is " + 9000765);
window.alert("Your " + 2 + " pizzas will be served at " + 8 + " pm");
window.alert("Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups.");
window.alert("Great people to fly with");
window.alert("Error " + 404);